### ISSUE TITLE
Puma gem dependency necessary?

### ISSUE THREAD

**Issue by dnd** [sensu-plugins/sensu-plugins-puma#3]
Given that this plugin checks the puma stats by sending a tcp/socket command is there really any purpose to having the puma gem itself as a non-development dependency in the gemspec? It would make sense if `pumactl` was being used, but I don't think that's the case here.

**Comment by majormoses** [comment]
Valid question for sure I just took a look and I don't see anything in there it might have been added for 2 reasons:
- previously needed puma (maybe in the mono repo days)
- wanted to make it easy for people to create new check and metric scripts

Either way I do not see something that requires it from a quick look. I would take a PR to remove it and if someone wants to re-add it again with a valid reason we can always cross that bridge again.

**Comment by dnd** [comment]
I will work on it, but the plugin could use an update in general. It doesn't cover stats output for puma >= 3.0.0 with regard to multiple workers, nor the most recent release 3.10.0 which also outputs GC stats. I'll get that added in and submit a PR next week probably.

**Comment by dnd** [comment]
So...what seemed like it would be simple at first has turned out to be more complicated. The puma dependency is technically currently required because the YAML `puma.state` file written by versions `< 3.0.0` includes `!ruby/object` directives that try to load into a Puma::Configuration instance. That's why the metric file currently requires `puma/configuration`, and the puma dependency in the gemspec. 

Interestingly, if I have successfully spelunked the puma versions correctly, the plugin in its current state technically requires version 2.16.0 of puma to be guaranteed to work correctly. This is the 2.x version that stopped including the `before_fork` hook which dumps to an empty `Proc` that cannot be loaded by YAML.

To further complicate matters, the `puma.state` file that is written in < 3 vs >= 3 is completely different. Not just in the ruby object directives, but structurally. Even to the point of using symbol vs string keys.

My plan right now regarding the config loading is to identify < v3 configs, and strip out the `!ruby/object` directives so that the yaml can load without having the puma dependency. From there the two values that are needed will be picked out `control_url` and `control_auth_token` appropriately. I'm also going to introduce a new option for each of them that the clients can pass when calling the plugin instead of having to use a state file

**Comment by dnd** [comment]
@majormoses when calling `output` with a metric that has a date value can you tell me how it's expected to be sent? I think it needs to be sent as an integer, but I can't remember for sure.

**Comment by eheydrick** [comment]
@dnd time values should be integers.

**Comment by dnd** [comment]
This issue has been resolved by PR #4
